### PR TITLE
Add integration test

### PR DESCRIPTION
**Pull request by dhirenmathur**
Implementation for #86 

Caveats that need to be fixed in further enhancements: 
1. The APIs still need auth token to work, current implementation involves manually adding this token to application.properties while testing, this means additional setup for contributor and additional setup for maintainer to store secrets in environment (Github, AWS etc) 
2) myQueues response does not have a constructor and thus is a little tricky to deserialise for assertions on returned value from test, current implementation only checks for 200 OK for myQueues and myTokens endpoints.

Value Add: 
Integration Tests to ensure that new changes do not break code
Can be used to implement CI/CD

Complexity Tradeoff:
Requires additional step of dev env setup

For review: @daltonfury42  (Note that the bearer token need to be added  into env explicitly in current implementation for any build to pass)

### CODE REVIEW

**Comment by daltonfury42** [comment]
For 1, what we should do is to mock the [AuthenticationFilter](https://github.com/SimplQ/simplQ-backend/blob/master/simplq/src/main/java/me/simplq/controller/advices/AuthenticationFilter.java) bean to set a dummy user to `loggedInUserInfo` and use it while testing.

For 2, can we just raise well defined issues, and we can let someone else take it? What do you think?

**Comment by dhirenmathur** [comment]
1) since this was supposed to be a so-clled "end to end" test I didn't want to mock out anything. My view was that we should fetch a real token from cognito and pass it on to the test request. What's your take, mocking should be okay? 

2)Yeah I don't mind it, will open an issue after this code is in master.

**Comment by daltonfury42** [comment]
Getting a live token might be difficult, we would have to create a test account and make his username/password public? 

I suggest that we mock this component for now, and later on, we can explore spring security and then properly do it the spring way .

https://stackoverflow.com/questions/44467133/spring-boot-authentication-for-integration-tests

**Comment by dhirenmathur** [comment]
I did look into spring security but I have a feeling it's not going to be as straight forward as it looks. 

Fair point, I didn't consider the implications of the username and password being public. Okay, I will try to mock out auth, shouldn't be too much effort.

**Review by daltonfury42 — APPROVED** [review]

**Comment by daltonfury42** [comment]
For now, we have introduced an anonymous user, for other reasons. This user can be used for our integration test too, for now. 

https://github.com/SimplQ/simplQ-backend/pull/98/files

@dhirenmathur It's not the nest solution, but it works... but this would change in future.

**Comment by dhirenmathur** [comment]
It just worked out of the box with "anonymous"? no additional setup? man that was so simple.

**Comment by daltonfury42** [comment]
No no. It was due to a change that I had made after you raised your PR: https://github.com/SimplQ/simplQ-backend/pull/95. See [this](https://github.com/SimplQ/simplQ-backend/pull/95/files#diff-fae7615cbc86b000f3f79590357f199e9abbc877a9dbd18bb487d01b01c03811R41) line.

Remember that anonymous user background login I had mentioned last time? I wanted to move away from that.

If not logged in, sent `Authorization: Bearer anonymous` with every request.
If logged in, set `Authorization: Bearer <jwt>`.

I think we should change to not send anything in case of anonymous requests. If the header is set, uthenticate, otherwise set as "anonymous"

**Comment by daltonfury42** [comment]
My thinking is, if you are logged in, the Queue IDs of all queues that you make will be stored at server side, it will be secure and won't be lost.

But if you are not logged it, you create an anonymous queue, and the queueId will be stored in you local storage. Anyone with the queueId will be able to manage the queue (weaker authorization) and if you clear your localstorage, you lost access to the queue. 

From the product side, we would encourage serious users who want security and to avoid data loss to login.

**Pull request merged**
